### ISSUE TITLE
META: Business logic workflows

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/janus-cluster-manager#27]
Part of https://github.com/cargomedia/puppet-cargomedia/issues/1080

Workflows:
- [ ] Multi-upstream registration and pairing https://github.com/cargomedia/puppet-cargomedia/issues/1080#issuecomment-234274634
- [x] Full Publisher-Subscriber workflow https://github.com/cargomedia/puppet-cargomedia/issues/1080#issuecomment-234226063
- [x] Regionalisation/Partitioning workflow https://github.com/cargomedia/puppet-cargomedia/issues/1080#issuecomment-233973981
- [x] Mountpoint create https://github.com/cargomedia/janus-cluster-manager/issues/27#issuecomment-233775556
- [x] Mountpoint destroy https://github.com/cargomedia/janus-cluster-manager/issues/27#issuecomment-233894317
- [x] Edge/Repeater/Origin member crash - fallback https://github.com/cargomedia/janus-cluster-manager/issues/27#issuecomment-233931212
- [x] Overview of RTP flow https://github.com/cargomedia/janus-cluster-manager/issues/27#issuecomment-233928756

---

UML can modified at https://www.websequencediagrams.com/ or e.g. https://www.lucidchart.com

**Comment by kris-lab** [comment]
Basic workflow for mountpoint **create**

<img width="734" alt="screen shot 2016-07-19 at 22 25 06" src="https://cloud.githubusercontent.com/assets/1843523/16967164/b1a92afe-4dff-11e6-8c59-289569a13667.png">

UML
```UML
participant Publisher;
participant Manager;
participant Origin;
participant Repeater;
participant Edge;
participant Subscriber;

Origin-->>Manager: register;
Repeater-->>Manager: register;
Edge-->>Manager: register;

Publisher-->>Origin: create mp;
Origin-->>Manager: new mp event;
Manager-->>Repeater: create mp;
Repeater-->>Manager: new mp event;
Manager-->>Edge: create mp;
Edge-->>Manager: new mp event;
Manager-->>Origin: watch-UDP for repeater;
Manager-->>Origin: watch-UDP for edge;

Publisher-->>Origin: RTP;
Origin-->>Repeater: RTP;
Repeater-->>Edge: RTP;
Subscriber-->>Edge: watch mp;
Edge-->>Subscriber: RTP;
```
you can modify at https://www.websequencediagrams.com/ or e.g. https://www.lucidchart.com

**Comment by kris-lab** [comment]
Basic workflow for mountpoint (mp) **DESTROY**

<img width="677" alt="screen shot 2016-07-20 at 10 06 23" src="https://cloud.githubusercontent.com/assets/1843523/16981264/b481bc52-4e61-11e6-9cd6-91e33ebb4e45.png">

UML
```UML
participant Publisher
participant Manager
participant Origin
participant Repeater
participant Edge
participant Subscriber

Publisher-->>Origin: destroy mp or close connection
Origin-->>Manager: mp destroyed event
Manager-->>Repeater: close connection
Repeater-->>Manager: mp destroyed event
Manager-->>Edge: close connection
Edge-->>Manager: mp destroyed event
```

**Comment by kris-lab** [comment]
Overview of RTP flow
<img width="822" alt="screen shot 2016-07-20 at 12 55 56" src="https://cloud.githubusercontent.com/assets/1843523/16985600/7654f67a-4e79-11e6-806c-dfb900f3e12b.png">

UML
```
participant Publisher
participant Origin
participant Repeater
participant Edge1
participant Edge2
participant Edge3
participant Subscriber1
participant Subscriber2
participant Subscriber3

Publisher-->>Origin: RTP
Origin-->>Repeater: RTP
Repeater-->>Edge1: RTP
Repeater-->>Edge2: RTP
Repeater-->>Edge3: RTP

Edge1-->>Subscriber1: RTP
Edge2-->>Subscriber2: RTP
Edge3-->>Subscriber3: RTP
```

**Comment by kris-lab** [comment]
Basic workflow for **ORIGIN CRASH** without handling multiple origin (SPOF)
<img width="911" alt="screen shot 2016-07-20 at 13 09 06" src="https://cloud.githubusercontent.com/assets/1843523/16985869/3e2a7192-4e7b-11e6-926f-18677765bb2f.png">

UML
```
participant Publisher
participant Manager
participant Origin
participant Repeater
participant Edge
participant Subscriber

Publisher-->>Subscriber: initial normal RTP streaming

Origin-->>Origin: process dies
Origin-->>Manager: WS connection closed
Manager-->>Manager: list connected downstreams
Manager-->>Repeater: close connection or destroy mp
Repeater-->>Manager: mp destroy event
Manager-->>Edge: close connection or destroy mp
Edge-->>Manager: mp destroy event
Edge-->>Edge: All subscribers are dropped
```

**Comment by njam** [comment]
Closing (repo deprecated)
