### ISSUE TITLE
META: Core features

### ISSUE THREAD

**Issue by tomaszdurka** [cargomedia/janus-cluster-manager#28]
Core: 
- [x] registering nodes
- [x] make single connection to janus server
- [x] unregistering nodes
- [x] establish session for receiving mount-points state (upgrade to superuser)
- [x] establish session for replicating upstream's state
- [ ] keeping _healthy_ state of each node

Some changes already pushed to https://github.com/tomaszdurka/janus-cluster-manager/tree/janus-gateway-adjustments

Additional tasks:
- [ ] implement multiple upstreams per node #25

**Comment by njam** [comment]
Closing (repo deprecated)
